name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.0

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Hosting Service
      # Add steps specific to your hosting service (e.g., Vercel, Netlify, AWS, etc.)
      # Example for deploying to Vercel:
      run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
